services:

  mongodb:
    image: mongo:8.0

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    ports:
      - "27017:27017"

    volumes:
      - mongodb_dev_data:/data/db

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\""
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: .
      dockerfile: Dockerfile.dev

    env_file:
      - .env

    ports:
      - "${APP_CONFIG__API__PORT:-8000}:8000"

    volumes:
      - ./app:/app/app

    depends_on:
      mongodb:
        condition: service_healthy


volumes:
  mongodb_dev_data:
